version: '{branch}.{build}'
branches:
  only:
  - v5.x
image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore Source\csla.test.sln
build:
  project: Source\csla.test.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - Csla.Test
    - csla.netcore.test
    - Csla.Validation.Test
